name: .NET
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone ðŸ“¥
      uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies ðŸ“¦
      run: dotnet restore
    - name: Build Library ðŸ”§
      run: dotnet build src/Org.Security.Cryptography.X509Extensions/Org.Security.Cryptography.X509Extensions.csproj --no-restore
    - name: Build Tests ðŸ”§
      run: dotnet build src/UnitTests/UnitTests.csproj --no-restore
    - name: Test With Code Coverage ðŸ§ª
      run: dotnet test src/UnitTests/UnitTests.csproj --no-build --framework Net5.0 /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=80 /p:ThresholdType=line /p:Exclude="[*]X509.EnduranceTest.Shared*" --verbosity normal
    - name: UploadToCodeCov â‡ª
      uses: codecov/codecov-action@v2
      with:
        files: src/UnitTests/coverage.Net5.0.opencover.xml
        verbose: true
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: $
        BRANCH: gh-pages
        FOLDER: src/Org.Security.Cryptography.X509Extensions/_site
